### ISSUE TITLE
[bug] SYS_ObjectSnapshot_SCH_TST - Access to entity 'TenantBillingUsageEvent' denied Stack Trace: null

### ISSUE THREAD

**Issue by NicolasGuigui** [pegros/PEG_SYS#9]
**Describe the bug**

During a package validation an error raised for the test execution SYS_ObjectSnapshot_SCH_TST.
No code update on SYS package has been done.

| Class Name | Method Name | Error Message |
|--------|--------|--------|
| SYS_ObjectSnapshot_SCH_TST | testExecute | Access to entity 'TenantBillingUsageEvent' denied Stack Trace: null |

**To Reproduce**
1. Go to developer console 
2. run test class : 'SYS_ObjectSnapshot_SCH_TST'

**Expected behavior**
No error raised

**Screenshots**
![image](https://github.com/user-attachments/assets/d4c734a8-207e-46b6-83b8-b957ccd456c7)
![image](https://github.com/user-attachments/assets/6a77cb62-f5f5-4748-9d61-35bb76fbd4cf)

**Desktop (please complete the following information):**
 - OS: Linux (Gitlab pipeline)  
 - Browser N/A

**Comment by pegros** [comment]
**TenantBillingUsageEvent** seems to be a new internal Salesforce event which does not support calling some methods of its schema description.
This is a new entry in the **SPECIAL_OBJECTS** static list of Salesforce objects with similar behaviour.
Unfortunately, calling these methods on these objects trigger internal Salesforce errors which may not be catched in Apex  via exceptions.
